// src/components/atomic/NowPlaying.tsx
import React, { useEffect, useState } from "react";
import Image from "next/image";
import Redis from "ioredis";

interface NowPlaying {
    albumName: string;
    albumImage: string;
    songName: string;
    artistName: string;
}

export const NowPlaying = () => {
    const [nowPlaying, setNowPlaying] = useState<NowPlaying | null>(null);

    useEffect(() => {
        const fetchData = async () => {
            try {
                let tokenData = null;
                var redis = new Redis(process.env.REDIS_URL as string);

                var spotifyData = await redis.get("spotifyData");

                if (spotifyData && JSON.parse(spotifyData).expires_in < new Date().getTime()) {

                    var data = new URLSearchParams();
                    data.append("refresh_token", JSON.parse(spotifyData).refresh_token);
                    data.append("grant_type", "refresh_token");

                    var apiReq = await fetch("https://accounts.spotify.com/api/token", {
                        method: "POST",
                        body: data,
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                            'Authorization': `Basic ${Buffer.from(process.env.SPOTIFY_CLIENT_ID + ":" + process.env.SPOTIFY_CLIENT_SECRET).toString('base64')}`
                        },
                    });

                    if (!apiReq.ok) {
                        const text = await apiReq.text();
                        console.error(`Spotify API Error [${apiReq.status}]:`, text);
                        tokenData = null;
                        return;
                    }

                    let apiRes;
                    try {
                        apiRes = await apiReq.json();
                    } catch (err) {
                        const text = await apiReq.text();
                        console.error("API response was not JSON:", text);
                        tokenData = null;
                        return;
                    }

                    if (apiRes.error) {
                        return Response.json({ error: apiRes.error });
                    } else {
                        var newData = {
                            access_token: apiRes.access_token,
                            expires_in: new Date().getTime() + apiRes.expires_in * 1000,
                            refresh_token: JSON.parse(spotifyData).refresh_token,
                        };

                        await redis.set("spotifyData", JSON.stringify(newData));

                        tokenData = newData;
                    }
                }

                tokenData = JSON.parse(spotifyData as string)
                // Get now playing
                const nowPlayingRequest = await fetch("https://api.spotify.com/v1/me/player/currently-playing", {
                    headers: {
                        "Authorization": `Bearer ${tokenData.access_token}`
                    }
                });

                if (!nowPlayingRequest.ok && nowPlayingRequest.status !== 204) {
                    console.error("Failed to fetch now playing");
                    return;
                }

                if (nowPlayingRequest.status === 204) {
                    setNowPlaying(null);
                    return;
                }

                const response = await nowPlayingRequest.json();

                if (!response) {
                    return;
                }

                if (nowPlayingRequest.ok && response && response.item) {
                    setNowPlaying({
                        albumName: response.item.album.name,
                        albumImage: response.item.album.images[0].url,
                        songName: response.item.name,
                        artistName: response.item.artists.length > 1
                            ? response.item.artists
                                .map((artist: any) => artist.name).join(", ")
                            : response.item.artists[0].name
                    });
                }
            } catch (error) {
                console.error("Error fetching data:", error);
            }
        };

        // Set up an interval to fetch data every 30 seconds
        fetchData(); // Initial fetch
        const interval = setInterval(fetchData, 30000);

        // Cleanup interval on component unmount
        return () => clearInterval(interval);
    }, []); // Empty dependency array since we're using setInterval

    if (!nowPlaying) {
        return null; // or a loading state
    }

    return (
        <React.Fragment>
            {nowPlaying && (
                <div className={`flex items-center gap-3`}>
                    <div className="group relative w-16 h-16">
                        <div className="opacity-0 absolute p-2 -top-12 right-1/2 translate-x-1/2 bg-neutral-800/70 rounded-md z-20 whitespace-nowrap w-max backdrop-blur-md group-hover:opacity-100 transition-all">
                            <p>{nowPlaying.albumName}</p>
                        </div>
                        <Image src={nowPlaying.albumImage} alt="Taksim" width={"640"} height={"640"} className="w-full h-full rounded-md object-cover" />
                        <div className="absolute top-0 left-0 right-0 bottom-0 bg-neutral-900/50 rounded-md z-0"></div>
                        <div className="absolute top-0 left-0 right-0 bottom-0 flex gap-1 items-center justify-center z-10">
                            <div className="w-1 h-4 bg-neutral-200 block bar"></div>
                            <div className="w-1 h-10 bg-neutral-200 block bar"></div>
                            <div className="w-1 h-6 bg-neutral-200 block bar"></div>
                            <div className="w-1 h-8 bg-neutral-200 block bar"></div>
                            <div className="w-1 h-5 bg-neutral-200 block bar"></div>
                        </div>
                    </div>
                    <div className="flex flex-col items-start justify-evenly h-full whitespace-nowrap">
                        <p className="text-xs text-neutral-400">Now Playing:</p>
                        <p className="text-neutral-200">{nowPlaying.songName}</p>
                        <p className="text-neutral-300 text-sm">{nowPlaying.artistName}</p>
                    </div>
                </div>
            )}
        </React.Fragment>
    )
}

// src/lib/components/atomic/now-playing.svelte
<script lang="ts">
	import { createTooltip, melt } from '@melt-ui/svelte';
	import { fade } from 'svelte/transition';

	var accessToken = $state();
	var songCover = $state();
	var songName = $state();
	var songArtist = $state();
	var songAlbum = $state();

	const getNowPlaying = async () => {
		var body = new URLSearchParams();
		body.append('grant_type', 'client_credentials');
		body.append('client_id', 'f327ea84f5ad48d5b1a25513f33af0e6');
		body.append('client_secret', '0f15ba7712e744c4808d5fa9a6f7dd9d');

		var request = await fetch('https://accounts.spotify.com/api/token', {
			method: 'POST',
			body: body,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded'
			}
		});

		var response = await request.json();
		console.log(response);
		accessToken = response.access_token;

		request = await fetch('https://api.spotify.com/v1/me/player/currently-playing', {
			headers: {
				Authorization: `Bearer ${accessToken}`
			}
		});

		response = await request.json();

		songCover = response.item.album.images[0].url;
		songName = response.item.name;
		if (response.item.artists.length > 1) {
			songArtist = response.item.artists.map((artist: any) => artist.name).join(', ');
		} else {
			songArtist = response.item.artists[0].name;
		}

		songAlbum = response.item.album.name;
	};

	// getNowPlaying();

	const {
		elements: { trigger, content, arrow },
		states: { open }
	} = createTooltip({
		positioning: {
			placement: 'top'
		},
		openDelay: 0,
		closeDelay: 0,
		closeOnPointerDown: false,
		forceVisible: true
	});
</script>

<div class="flex w-full max-w-96 items-center gap-3">
	<div use:melt={$trigger} class="relative aspect-1 h-14">
		<div class="absolute inset-0 flex items-center justify-center gap-1 bg-black/30">
			<span
				class="max-h-4/5 inline-block h-2/5 w-1 bg-white"
				style="animation: up-and-down 1.3s ease infinite alternate; animation-delay: 0s;"
			></span>
			<span
				class="max-h-4/5 inline-block h-3/5 w-1 bg-white"
				style="animation: up-and-down 1.3s ease infinite alternate; animation-delay: 0.2s;"
			></span>
			<span
				class="max-h-4/5 inline-block h-1/5 w-1 bg-white"
				style="animation: up-and-down 1.3s ease infinite alternate; animation-delay: 0.4s;"
			></span>
			<span
				class="max-h-4/5 inline-block h-4/5 w-1 bg-white"
				style="animation: up-and-down 1.3s ease infinite alternate; animation-delay: 0.6s;"
			></span>
		</div>
		<img
			src="https://i.scdn.co/image/ab67616d00001e02586d3ac510fd1220ecfb97eb"
			alt="Sana Güvenmiyorum - Dedub Sessions"
			class="aspect-1 h-14 rounded-md border border-gray-300"
		/>
	</div>
	<div class="flex w-full flex-col justify-center overflow-hidden">
		<span class="text-xs font-light text-gray-300">Now Playing:</span>
		<span class="truncate text-sm font-bold">Sana Güvenmiyorum - Dedub Sessions</span>
		<span class="text-sm">Dedublüman, Aleyna Tilki</span>
	</div>
</div>

{#if $open}
	<div
		use:melt={$content}
		transition:fade={{ duration: 100 }}
		class="z-10 rounded-lg bg-slate-950 shadow-lg"
	>
		<div use:melt={$arrow}></div>
		<p class="px-2 py-1 text-sm text-white">Sana Güvenmiyorum (Dedub Sessions)</p>
	</div>
{/if}
